services:

  # La base de donnees MySQL qui stocke tout
  database:
    image: mysql:8.0
    container_name: upcycle_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: upcycle_connect
    volumes:
      - data_db:/var/lib/mysql
      - ./base_remplie.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - net_upcycle

  # L'API Go qui gère toute la logique
  api:
    build:
      context: .
      dockerfile: ./api_backend/dockerfile
    container_name: upcycle_api
    restart: unless-stopped
    # Plus d'exposition publique du 8080 comme ca l'API n'est joignable qu'en interne
    depends_on:
      database:
        condition: service_healthy
    networks:
      - net_upcycle


  web:
    build:
      context: .
      dockerfile: dockerfile.php
    container_name: upcycle_web
    restart: unless-stopped
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      - api
    networks:
      - net_upcycle

networks:
  net_upcycle:
    driver: bridge

volumes:
  data_db: